version: '3'

services:
  mysql:
    image: mysql:8.0
    restart: always
    container_name: nini-chat-db
    ports:
      - "33060:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=nini-chat-db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=mipasswordxd
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
    external: false